// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjuv-MXi7cPBjOAra9A5KCYkl7CZ5kfP0',
    appId: '1:751277100021:web:0bb371fef2fd677a8faebc',
    messagingSenderId: '751277100021',
    projectId: 'user-management-da458',
    authDomain: 'user-management-da458.firebaseapp.com',
    storageBucket: 'user-management-da458.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEER3CGejP9TWKLdxYG9ZVVVdoNVYtawk',
    appId: '1:751277100021:android:dfc4d79b1e3464ea8faebc',
    messagingSenderId: '751277100021',
    projectId: 'user-management-da458',
    storageBucket: 'user-management-da458.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf6ylMJJtWsu51mrTdeL6tX2pYGaOL9lA',
    appId: '1:751277100021:ios:f355b995a204e7fa8faebc',
    messagingSenderId: '751277100021',
    projectId: 'user-management-da458',
    storageBucket: 'user-management-da458.appspot.com',
    iosClientId: '751277100021-4g9s7bvls1s4l1ja95d523dmfo06cd48.apps.googleusercontent.com',
    iosBundleId: 'com.example.usersManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf6ylMJJtWsu51mrTdeL6tX2pYGaOL9lA',
    appId: '1:751277100021:ios:7ee107e63d3548ab8faebc',
    messagingSenderId: '751277100021',
    projectId: 'user-management-da458',
    storageBucket: 'user-management-da458.appspot.com',
    iosClientId: '751277100021-02ava2nf7lomvf0rdnpfiu0bbs6gjnn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.usersManagement.RunnerTests',
  );
}
